name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v4

    - name: Validate Go modules
      run: ./scripts/validate

    - name: Build
      env:
        CROSS: 1
      run: ./scripts/build

    - name: Test
      run: ./scripts/test

    - name: Package
      run: |
        ./scripts/package
        ls -lR dist/artifacts
        # Stage binary for packaging step
        cp -r ./bin/* ./package/
  
    - name: Docker Build
      uses: docker/build-push-action@v5
      with:
        push: false
        context: package
        tags: rancher/cli2:$GITHUB_REF_NAME

  fossa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication

    steps:
      - name: Load Secrets from Vault
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/fossa/credentials token | FOSSA

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check FOSSA compliance
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ env.FOSSA }}

